/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScheduledRouteRouteImport } from './routes/scheduled/route'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as TemplatesRouteRouteImport } from './routes/templates/route'
import { Route as ThreadAccountIdThreadIdRouteImport } from './routes/thread.$accountId.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduledRouteRoute = ScheduledRouteRouteImport.update({
  id: '/scheduled',
  path: '/scheduled',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRouteRoute = TemplatesRouteRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadAccountIdThreadIdRoute = ThreadAccountIdThreadIdRouteImport.update({
  id: '/thread/$accountId/$threadId',
  path: '/thread/$accountId/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/scheduled': typeof ScheduledRouteRoute
  '/settings': typeof SettingsRouteRoute
  '/templates': typeof TemplatesRouteRoute
  '/thread/$accountId/$threadId': typeof ThreadAccountIdThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/scheduled': typeof ScheduledRouteRoute
  '/settings': typeof SettingsRouteRoute
  '/templates': typeof TemplatesRouteRoute
  '/thread/$accountId/$threadId': typeof ThreadAccountIdThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/scheduled': typeof ScheduledRouteRoute
  '/settings': typeof SettingsRouteRoute
  '/templates': typeof TemplatesRouteRoute
  '/thread/$accountId/$threadId': typeof ThreadAccountIdThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/scheduled'
    | '/settings'
    | '/templates'
    | '/thread/$accountId/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/scheduled'
    | '/settings'
    | '/templates'
    | '/thread/$accountId/$threadId'
  id:
    | '__root__'
    | '/'
    | '/scheduled'
    | '/settings'
    | '/templates'
    | '/thread/$accountId/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ScheduledRouteRoute: typeof ScheduledRouteRoute
  SettingsRouteRoute: typeof SettingsRouteRoute
  TemplatesRouteRoute: typeof TemplatesRouteRoute
  ThreadAccountIdThreadIdRoute: typeof ThreadAccountIdThreadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduled': {
      id: '/scheduled'
      path: '/scheduled'
      fullPath: '/scheduled'
      preLoaderRoute: typeof ScheduledRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thread/$accountId/$threadId': {
      id: '/thread/$accountId/$threadId'
      path: '/thread/$accountId/$threadId'
      fullPath: '/thread/$accountId/$threadId'
      preLoaderRoute: typeof ThreadAccountIdThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ScheduledRouteRoute: ScheduledRouteRoute,
  SettingsRouteRoute: SettingsRouteRoute,
  TemplatesRouteRoute: TemplatesRouteRoute,
  ThreadAccountIdThreadIdRoute: ThreadAccountIdThreadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
